/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSignatureDishesRouteImport } from './routes/_layout/signature-dishes'
import { Route as LayoutReserveRouteImport } from './routes/_layout/reserve'
import { Route as LayoutMenuRouteImport } from './routes/_layout/menu'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutCelebrationsRouteImport } from './routes/_layout/celebrations'
import { Route as LayoutBarAndDrinksRouteImport } from './routes/_layout/bar-and-drinks'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSignatureDishesRoute = LayoutSignatureDishesRouteImport.update({
  id: '/signature-dishes',
  path: '/signature-dishes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReserveRoute = LayoutReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMenuRoute = LayoutMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCelebrationsRoute = LayoutCelebrationsRouteImport.update({
  id: '/celebrations',
  path: '/celebrations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBarAndDrinksRoute = LayoutBarAndDrinksRouteImport.update({
  id: '/bar-and-drinks',
  path: '/bar-and-drinks',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/bar-and-drinks': typeof LayoutBarAndDrinksRoute
  '/celebrations': typeof LayoutCelebrationsRoute
  '/contact': typeof LayoutContactRoute
  '/menu': typeof LayoutMenuRoute
  '/reserve': typeof LayoutReserveRoute
  '/signature-dishes': typeof LayoutSignatureDishesRoute
}
export interface FileRoutesByTo {
  '/bar-and-drinks': typeof LayoutBarAndDrinksRoute
  '/celebrations': typeof LayoutCelebrationsRoute
  '/contact': typeof LayoutContactRoute
  '/menu': typeof LayoutMenuRoute
  '/reserve': typeof LayoutReserveRoute
  '/signature-dishes': typeof LayoutSignatureDishesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/bar-and-drinks': typeof LayoutBarAndDrinksRoute
  '/_layout/celebrations': typeof LayoutCelebrationsRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/menu': typeof LayoutMenuRoute
  '/_layout/reserve': typeof LayoutReserveRoute
  '/_layout/signature-dishes': typeof LayoutSignatureDishesRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bar-and-drinks'
    | '/celebrations'
    | '/contact'
    | '/menu'
    | '/reserve'
    | '/signature-dishes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bar-and-drinks'
    | '/celebrations'
    | '/contact'
    | '/menu'
    | '/reserve'
    | '/signature-dishes'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/bar-and-drinks'
    | '/_layout/celebrations'
    | '/_layout/contact'
    | '/_layout/menu'
    | '/_layout/reserve'
    | '/_layout/signature-dishes'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/signature-dishes': {
      id: '/_layout/signature-dishes'
      path: '/signature-dishes'
      fullPath: '/signature-dishes'
      preLoaderRoute: typeof LayoutSignatureDishesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reserve': {
      id: '/_layout/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof LayoutReserveRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/menu': {
      id: '/_layout/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof LayoutMenuRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/celebrations': {
      id: '/_layout/celebrations'
      path: '/celebrations'
      fullPath: '/celebrations'
      preLoaderRoute: typeof LayoutCelebrationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bar-and-drinks': {
      id: '/_layout/bar-and-drinks'
      path: '/bar-and-drinks'
      fullPath: '/bar-and-drinks'
      preLoaderRoute: typeof LayoutBarAndDrinksRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBarAndDrinksRoute: typeof LayoutBarAndDrinksRoute
  LayoutCelebrationsRoute: typeof LayoutCelebrationsRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutMenuRoute: typeof LayoutMenuRoute
  LayoutReserveRoute: typeof LayoutReserveRoute
  LayoutSignatureDishesRoute: typeof LayoutSignatureDishesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBarAndDrinksRoute: LayoutBarAndDrinksRoute,
  LayoutCelebrationsRoute: LayoutCelebrationsRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutMenuRoute: LayoutMenuRoute,
  LayoutReserveRoute: LayoutReserveRoute,
  LayoutSignatureDishesRoute: LayoutSignatureDishesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
